# fly.toml app configuration file generated for tired-ollama on 2025-03-08T18:29:42+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tired-ollama'
primary_region = 'ord'
swap_size_mb = 8192

[env]
OLLAMA_PROXY_PORT = '8080'
OLLAMA_PROXY_IDLE_TIME = '20'
OLLAMA_PROXY_ORIGIN = 'http://localhost:11434'

[mounts]
source = "juicefs_cache"
destination = "/var/jfsCache"

[[services]]
internal_port = 8080
protocol = "tcp"
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0

[services.concurrency]
type = "requests"
soft_limit = 5
hard_limit = 25

[[services.ports]]
handlers = ['http']
port = 11434

[[services.ports]]
handlers = ['http']
port = 80

[[vm]]
memory = '32gb'
cpu_kind = 'performance'
cpus = 8
gpu_kind = "l40s"
gpus = 1
